#!/usr/bin/php
<?php /* -*- mode: php; mode: mmm; coding: utf-8-unix; -*- */
/**
 *
 * Remote Exec
 *
 * <p>Utility to execute simple file system operations on a remote
 * server using the localexec script through ssh.
 *
 * <p>This is really the test script for the sys-remote-filesys.inc
 *    module and remote_filesystem_c class.
 *
 *
 * <p><b>Copyright</b>
 *
 * <p>Copyright (c) 2009-2010 by Sam Azer, All Rights Reserved.
 *
 * <p>This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * <p>This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * <p>You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * @author Sam Azer <sam@azertech.net>
 * @version 0.01a
 * @package sysbackup
 * @subpackage sys-test
 * @license http://www.gnu.org/licenses/gpl.html GPL
 * @copyright 2011 by Sam Azer, All rights reserved
 * @link http://www.azertech.net/
 * @link http://www.samazer.net/about
 *
 */



include "lib/general-tee.inc";
include "lib/sys-remote-filesys.inc";


$binary  = "/usr/bin/ssh";
$options = "";


/**
 *
 * @package sysbackup
 * @subpackage sys-test
 *
 */
class remote_exec_c extends teelog_c
{
   var $progname;
   var $command;
   var $params;

   var $remsys;


   function params_show()
   {
      $cmdl = "";
      foreach ( $this->params as $p )
         $cmdl = $cmdl
               . ($cmdl > "" ? ", " : "")
               . $p
               ;

      $this->tee( TEELOG_TXTWARNING . "received {$this->command}( {$cmdl} )" );
   }


   function params_showneeded( $plist )
   {
      $list = "";
      foreach ( $plist as $p )
         $list = $list
               . ($list > "" ? ", " : "")
               . $p
               ;

      $this->tee( TEELOG_TXTWARNING . "was expecting {$this->command}( {$list} )" );
   }



   function params_required( $plist )
   {
      if ( count( $this->params ) == count( $plist ) )
         return false;

      $this->params_showneeded( $plist );
      $this->params_show();
      $this->fatal( "invalid parameter count for the '{$this->command}' command" );
   }



   function fatal_file_error()
   {
      $this->fatal( $this->remsys->last_error() );
   }



   function result( $r )
   {
      if ( is_bool($r) )
      {
         $this->tee( LOCALEXEC_TXTRESULT . ($r ? "true" : "false") );
         return false;
      }

      $this->tee( LOCALEXEC_TXTRESULT . $r );
      return false;
   }



   function exec()
   {
      switch ( $this->command )
      {
         case "disk_free_space":
            $this->params_required( array( "path" ) );

            if ( ($r = $this->remsys->disk_free_space( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "disk_total_space":
            $this->params_required( array( "path" ) );

            if ( ($r = $this->remsys->disk_total_space( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;


         case "sha1_file":
            $this->params_required( array( "path" ) );

            if ( ($r = $this->remsys->sha1_file( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;


         case "realpath":
            $this->params_required( array( "path" ) );

            if ( ($r = $this->remsys->realpath( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "readlink":
            $this->params_required( array( "path" ) );

            if ( ($r = $this->remsys->readlink( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;



         case "filesize":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->filesize( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "filetype":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->filetype( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "fileatime":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->fileatime( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "filectime":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->filectime( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "filemtime":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->filemtime( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "fileperms":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->fileperms( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "linkinfo":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->linkinfo( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;



         case "filegroup":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->filegroup( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;

         case "fileowner":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->fileowner( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;



         case "readfile":
         case "file_get_contents":
         case "file":
            $this->params_required( array( "path/filename" ) );

            if ( ($r = $this->remsys->readfile( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->tee( trim($r) );
            break;



         case "file_exists":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->file_exists( $this->params[0] ));
            break;

         case "is_dir":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->is_dir( $this->params[0] ));
            break;

         case "is_file":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->is_file( $this->params[0] ));
            break;

         case "is_link":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->is_link( $this->params[0] ));
            break;

         case "is_readable":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->is_readable( $this->params[0] ));
            break;

         case "is_writable":
         case "is_writeable":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->is_writable( $this->params[0] ));
            break;

         case "is_executable":
            $this->params_required( array( "path/filename" ) );
            $this->result( $this->remsys->is_executable( $this->params[0] ));
            break;



         case "chgrp":
            $this->params_required( array( "filename", "group" ) );
            $this->result( $this->remsys->chgrp( $this->params[0], $this->params[1] ));
            break;

         case "chmod":
            $this->params_required( array( "filename", "mode" ) );
            $this->result( $this->remsys->chmod( $this->params[0], $this->params[1] ));
            break;

         case "chown":
            $this->params_required( array( "filename", "user" ) );
            $this->result( $this->remsys->chown( $this->params[0], $this->params[1] ));
            break;

         case "lchgrp":
            $this->params_required( array( "filename", "group" ) );
            $this->result( $this->remsys->lchgrp( $this->params[0], $this->params[1] ));
            break;

         case "lchown":
            $this->params_required( array( "filename", "user" ) );
            $this->result( $this->remsys->lchown( $this->params[0], $this->params[1] ));
            break;



         case "glob":
            $this->params_required( array( "cwd", "pattern", "flags" ) );

            if ( ($r = $this->remsys->glob( $this->params[0], 
                                             $this->params[1], 
                                             $this->params[2] )) === false )
               $this->fatal_file_error();

            foreach ( $r as $v )
               $this->tee( $v );

            break;



         case "stat":
         case "lstat":
            $this->params_required( array( "path/filename" ) );

            if ( $this->command == "stat" )
               $r = $this->remsys->stat( $this->params[0] );
            else $r = $this->remsys->lstat( $this->params[0] );

            if ( $r === false )
               $this->fatal_file_error();

            foreach ( $r as $i => $v )
               if ( is_string( $i ) )
                  $this->tee( "{$i}: {$v}" );
            break;



         case "copy":
            $this->params_required( array( "source", "dest" ) );
            if ( ($r = $this->remsys->copy( $this->params[0], $this->params[1] )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;

         case "rename":
            $this->params_required( array( "source", "dest" ) );
            if ( ($r = $this->remsys->rename( $this->params[0], $this->params[1] )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;

         case "can_hardlink":
            $this->params_required( array( "target", "link" ) );
            $this->result( $this->remsys->can_hardlink($this->params[0], $this->params[1]) );
            break;



         case "link":
            $this->params_required( array( "target", "link" ) );
            if ( ($r = $this->remsys->link( $this->params[0], $this->params[1] )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;

         case "symlink":
            $this->params_required( array( "target", "link" ) );
            if ( ($r = $this->remsys->symlink( $this->params[0], $this->params[1] )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;

         case "list_expired_items":
            $this->params_required( array( "path", "max_items" ) );

            if ( ($r = $this->remsys->list_expired_items($this->params[0], $this->params[1])) === false )
               $this->fatal_file_error();

            var_dump( $r );
            exit();
            break;

         case "remove_expired_items":
            $this->params_required( array( "path", "max_items", "debug" ) );

            if ( ($r = $this->remsys->remove_expired_items($this->params[0], $this->params[1], $this->params[2])) === false )
               $this->fatal_file_error();

            $this->result( $r );
            break;




         case "mkdir":
            $this->params_required( array( "path" ) );
            if ( ($r = $this->remsys->mkdir( $this->params[0], 0777, true )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;

         case "rmdir":
            $this->params_required( array( "path" ) );
            if ( ($r = $this->remsys->rmdir( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;

         case "unlink":
            $this->params_required( array( "path/filename" ) );
            if ( ($r = $this->remsys->unlink( $this->params[0] )) === false )
               $this->fatal_file_error();

            $this->result( true );
            break;


         default:
            $this->fatal( "unknown command: {$this->command}" );
      }
   }



   function help()
   {
      $help_info = array( "disk_free_space"  => array( "path" ),
                          "disk_total_space" => array( "path" ),
                          "realpath"         => array( "path" ),
                          "readlink"         => array( "path" ),
                          "filesize"         => array( "path/filename" ),
                          "filetype"         => array( "path/filename" ),
                          "fileatime"        => array( "path/filename" ),
                          "filectime"        => array( "path/filename" ),
                          "filemtime"        => array( "path/filename" ),
                          "fileperms"        => array( "path/filename" ),
                          "linkinfo"         => array( "path/filename" ),

                          "filegroup"        => array( "path/filename" ),
                          "fileowner"        => array( "path/filename" ),

                          "readfile"         => array( "path/filename" ),

                          "file_exists"      => array( "path/filename" ),
                          "is_dir"           => array( "path/filename" ),
                          "is_file"          => array( "path/filename" ),
                          "is_link"          => array( "path/filename" ),
                          "is_readable"      => array( "path/filename" ),

                          "is_writable"      => array( "path/filename" ),
                          "is_executable"    => array( "path/filename" ),

                          "chgrp"            => array( "filename", "group" ),
                          "chmod"            => array( "filename", "mode" ),
                          "chown"            => array( "filename", "user" ),
                          "lchgrp"           => array( "filename", "group" ),
                          "lchown"           => array( "filename", "user" ),

                          "glob"             => array( "cwd", "pattern", "flags" ),

                          "stat"             => array( "path/filename" ),
                          "lstat"            => array( "path/filename" ),

                          "copy"             => array( "source", "dest" ),
                          "rename"           => array( "source", "dest" ),
                          "link"             => array( "target", "link" ),
                          "symlink"          => array( "target", "link" ),

                          "mkdir"            => array( "path" ),
                          "rmdir"            => array( "path" ),
                          "unlink"           => array( "path/filename" ),
                        );

      $hdr = <<< EOT

Remote Exec Utility. This utility will execute 
standard PHP filesystem functions on a remote 
server, through SSH, using a corresponding 
localexec script. Returns values are written 
to stdout as text.

Usage: remexec <key> <user@server> <command> <param> [...<param>]

Where each <command> is essentially a call to the 
equivalent PHP function. See the standard PHP docs
at http://www.php.net/manual/en/ref.filesystem.php
for detailed function descriptions.

Following is a list of <command>s and their para-
meters. Note that some commands, such as mkdir() 
and glob(), assume parameters that are not the 
same as the documented PHP defaults. See the 
source code for details.

EOT;

      $this->tee( $hdr );
      foreach( $help_info as $cmd => $plist )
      {
         $list = "";
         foreach ( $plist as $p )
            $list = $list
                  . ($list > "" ? ", " : "")
                  . $p
                  ;

         $this->tee( "{$cmd}( {$list} )" );
      }

      $this->tee("");
      $this->tee("");
   }


   function __construct( $fn = "" )
   {
      parent::__construct( $fn );
   }


   function main( $argv )
   {
      parent::__construct();

      global $binary, $key, $options, $user, $server;

      if ( count( $argv ) == 1 )
      {
         $this->help();
         exit(0);
      }

      if ( count( $argv ) >= 3 )
      {
         $x      = explode( "@", $argv[2] );
         $key    = $argv[1];
         $user   = $x[0];
         $server = $x[1];
      }

      $this->progname = $argv[0];
      $this->command  = "";

      if ( count( $argv ) >= 4 )
      {
         $this->command  = $argv[3];

         $this->params   = array();
         for ( $i = 4; $i < count( $argv ); $i++ )
             $this->params[] = stripcslashes(urldecode( $argv[$i] ));
      }

      if ( ($this->command == "")
        || ($this->command == "help")
        || ($this->command == "-h")
        || ($this->command == "--help") )
      {
         $this->help();
         exit(0);
      }

      $this->remsys = new remote_filesystem_c( $this, $binary, $key, $options, $user, $server );
      $this->exec();
   }
}



$exec_obj = new remote_exec_c();
$exec_obj->main( $argv );
return 0;

